development:
  sessions:
    default:
      database: flash_message_service_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: flash_message_service_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      hosts:
        - kahana.mongohq.com:10029
      database: app25980312
      username: flash_message_service
      password: beginatthebeginning